-- Run this in the Supabase SQL Editor

-- 1. SPOTS Table
create table spots (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  name text,
  price numeric,
  available int,
  lat float,
  lng float,
  image_url text,
  trust_level int default 3,
  vehicle_type text default 'car',
  unavailable_dates jsonb default '[]'::jsonb,
  unavailable_days jsonb default '[]'::jsonb,
  unavailable_reason text,
  amenities jsonb default '[]'::jsonb,
  is_premium boolean default false,
  qr_code_id text,
  owner_lat float,
  owner_lng float
);

-- 2. USERS Table
create table users (
  id text primary key, -- We will use 'user_123' for the demo user for continuity
  name text,
  points int default 0,
  tier text default 'Bronze',
  wallet_balance numeric default 0.00
);

-- 3. TRANSACTIONS Table
create table transactions (
  id bigint generated by default as identity primary key,
  user_id text references users(id),
  type text,
  amount numeric,
  user_name text,
  payment_ref text,
  timestamp numeric,
  date text,
  spot_id bigint references spots(id),
  spot_name text,
  vehicle_plate text,
  created_at timestamptz default now()
);

-- 4. SESSIONS Table (Active Parking)
create table sessions (
  id bigint generated by default as identity primary key,
  spot_id bigint references spots(id),
  user_name text,
  vehicle_plate text,
  start_time numeric,
  expiry_time numeric,
  price numeric,
  payment_ref text,
  created_at timestamptz default now()
);

-- 5. Seed Data (Preserve the Demo User)
insert into users (id, name, points, tier, wallet_balance)
values ('user_123', 'Alex Driver', 120, 'Bronze', 0.00)
on conflict (id) do nothing;
